#!/usr/bin/env python3
"""build_appendix.py — assemble building_website/appendix.tex.

For every available row in `website/data/manifest.json`, emit a per-row
block containing:

  * a heading line  "Definition: <title>"  or  "Claim: <title>"
  * two side-by-side minipages — original LN tex on the left, Lean code
    on the right
  * a tight Notes area for hand-written annotations

Left-column source is the original (simpler) LN tex pulled from
`lecture-notes/lecture_notes/graphs.tex` by row marker (`% def_3_1`,
`% claim_3_2`, ...), with the outer theorem-env wrapper stripped — same
shape the website renders as the default panel view.

Re-running the script preserves whatever sits between each row's
`% NOTES-BEGIN <ref>` / `% NOTES-END <ref>` markers, so notes are never
overwritten when panel data is refreshed.

This script is purely additive — it does not touch panel JSONs, the
website, or any other builder.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = REPO_ROOT / "building_website" / "website" / "data"
LN_PATH = REPO_ROOT / "lecture-notes" / "lecture_notes" / "graphs.tex"
OUT_PATH = REPO_ROOT / "building_website" / "appendix.tex"

KIND_LABEL = {"def": "Definition", "claim": "Claim"}
THEOREM_ENVS = ["Def", "Not", "Lem", "Rem", "Cor", "Prop", "Thm", "Conj"]

NOTES_BLOCK_RE = re.compile(
    r"% NOTES-BEGIN (?P<ref>[A-Za-z0-9_]+)\n(?P<body>.*?)\n% NOTES-END (?P=ref)",
    re.DOTALL,
)

PREAMBLE = r"""% appendix.tex — generated by building_website/scripts/build_appendix.py.
% Re-running preserves whatever sits between each row's
% `% NOTES-BEGIN <ref>` / `% NOTES-END <ref>` markers.
%
% Preamble (documentclass, packages, custom macros, minted setup) is
% supplied by the wrapping document; this file only emits body content.

%% ====== Size / layout knobs — tweak freely ===================
% Font size of the LN tex on the left.
\providecommand{\appendixTexSize}{\footnotesize}
% Font size of the Lean code on the right.
\providecommand{\appendixLeanSize}{\footnotesize}
% Width of each side-by-side column (twice this + a tiny gap = \textwidth).
\providecommand{\appendixColWidth}{0.495\textwidth}
% Vertical space reserved for hand-written notes under each row.
\providecommand{\appendixNotesGap}{1em}
%% ==============================================================
"""


def read_ln_text() -> str:
    return LN_PATH.read_text()


def parse_ln_row(ln_text: str, ref: str):
    """Return (env, bracketed_title_or_None, full_env_block) for the row's
    LN tex block, or None if no row marker / no theorem env found."""
    m = re.search(rf"^% {re.escape(ref)}\b.*$", ln_text, re.MULTILINE)
    if not m:
        return None
    start = m.end()
    nxt = re.search(r"^% (def|claim)_\d+_\d+\b", ln_text[start:], re.MULTILINE)
    end = start + nxt.start() if nxt else len(ln_text)
    block = ln_text[start:end]
    candidates = []
    for env in THEOREM_ENVS:
        for bm in re.finditer(rf"\\begin\{{{env}\}}(\[[^\]]*\])?", block):
            candidates.append((bm.start(), env, bm))
    if not candidates:
        return None
    candidates.sort()
    pos, env, bm = candidates[0]
    bracket = bm.group(1)
    title = bracket[1:-1] if bracket else None
    em = re.search(rf"\\end\{{{env}\}}", block[pos:])
    if not em:
        return None
    full = block[pos : pos + em.end()]
    return env, title, full


def strip_env_wrapper(full: str, env: str) -> str:
    body = re.sub(
        rf"^\\begin\{{{env}\}}(\[[^\]]*\])?[ \t]*\n?", "", full, count=1
    )
    body = re.sub(rf"\n?[ \t]*\\end\{{{env}\}}\s*$", "", body, count=1)
    return body.strip("\n")


def heading_title(panel: dict, ln_parsed) -> str:
    kind_label = KIND_LABEL.get(panel["kind"], panel["kind"].capitalize())
    if ln_parsed and ln_parsed[1]:
        title = ln_parsed[1]
    else:
        title = panel["tex_statement"]["env_title"]
    return f"{kind_label}: {title}"


def left_column(panel: dict, ln_parsed) -> str:
    if ln_parsed is None:
        # Fallback: derive from canonical tex_statement.raw if LN parse fails.
        raw = panel["tex_statement"]["raw"]
        m = re.search(r"\\begin\{document\}(.*?)\\end\{document\}", raw, re.DOTALL)
        return (m.group(1) if m else raw).strip()
    env, _, full = ln_parsed
    return strip_env_wrapper(full, env)


def right_column(panel: dict) -> str:
    blocks = [b["code"].rstrip() for b in panel.get("lean_blocks", [])]
    return "\n\n".join(blocks)


def render_row(panel: dict, ln_text: str, preserved_notes: str) -> str:
    ref = panel["ref"]
    ln_parsed = parse_ln_row(ln_text, ref)
    title = heading_title(panel, ln_parsed)
    left = left_column(panel, ln_parsed)
    right = right_column(panel)
    notes = preserved_notes if preserved_notes.strip() else ""
    return (
        f"%% ROW-BEGIN {ref}\n"
        f"\\noindent\\textbf{{{title}}}\\par\\smallskip\n"
        f"\\noindent\\begin{{minipage}}[t]{{\\appendixColWidth}}\\appendixTexSize\n"
        f"{left}\n"
        f"\\end{{minipage}}\\hfill\\begin{{minipage}}[t]{{\\appendixColWidth}}\n"
        f"\\begin{{minted}}[fontsize=\\appendixLeanSize]{{lean4}}\n"
        f"{right}\n"
        f"\\end{{minted}}\n"
        f"\\end{{minipage}}\\par\n"
        f"\\smallskip{{\\small\\textit{{Notes:}}}}~%\n"
        f"% NOTES-BEGIN {ref}\n"
        f"{notes}\n"
        f"% NOTES-END {ref}\n"
        f"\\vspace{{\\appendixNotesGap}}\n"
        f"%% ROW-END {ref}\n"
    )


def load_existing_notes(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    return {
        m.group("ref"): m.group("body")
        for m in NOTES_BLOCK_RE.finditer(path.read_text())
    }


def main() -> None:
    manifest = json.loads((DATA_DIR / "manifest.json").read_text())
    ln_text = read_ln_text()
    preserved = load_existing_notes(OUT_PATH)

    out = [PREAMBLE]

    for chapter in manifest["chapters"]:
        for section in chapter["sections"]:
            sec = section["section"]
            out.append(f"\\section*{{Section {sec}}}\n")
            for row in section["rows"]:
                if not row.get("available", False):
                    continue
                panel = json.loads((DATA_DIR / f"{row['ref']}.json").read_text())
                out.append(render_row(panel, ln_text, preserved.get(row["ref"], "")))

    OUT_PATH.write_text("\n".join(out).rstrip() + "\n")
    print(f"Wrote {OUT_PATH} ({OUT_PATH.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
