#!/usr/bin/env python3
"""build_appendix.py — assemble building_website/appendix.tex.

For every available row in `website/data/manifest.json`, emit a per-row
block containing:

  * a heading line   "Definition: <env_title>"  or  "Claim: <env_title>"
  * two minipages — LN tex on the left, Lean code on the right
  * a Notes area for hand-written annotations

Re-running the script preserves whatever sits between each row's
`% NOTES-BEGIN <ref>` / `% NOTES-END <ref>` markers, so notes are never
overwritten when panel data is refreshed.

This script is purely additive — it does not touch panel JSONs, the
website, or any other builder.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = REPO_ROOT / "building_website" / "website" / "data"
OUT_PATH = REPO_ROOT / "building_website" / "appendix.tex"

KIND_LABEL = {"def": "Definition", "claim": "Claim"}

DOC_BODY_RE = re.compile(r"\\begin\{document\}(.*?)\\end\{document\}", re.DOTALL)

NOTES_BLOCK_RE = re.compile(
    r"% NOTES-BEGIN (?P<ref>[A-Za-z0-9_]+)\n(?P<body>.*?)\n% NOTES-END (?P=ref)",
    re.DOTALL,
)

ROW_SEP = (
    "%% ============================================================\n"
)


def extract_tex_body(raw: str) -> str:
    """Return the content between `\\begin{document}` and `\\end{document}`,
    stripped of per-row metadata scaffolding (`\\def\\rowref`,
    `\\phantomsection`, `% ref:`, `% title:`)."""
    m = DOC_BODY_RE.search(raw)
    body = m.group(1) if m else raw
    kept = []
    for line in body.splitlines():
        s = line.strip()
        if s.startswith("% ref:"):
            continue
        if s.startswith("% title:"):
            continue
        if s.startswith("\\def\\rowref"):
            continue
        if s.startswith("\\phantomsection"):
            continue
        kept.append(line)
    while kept and not kept[0].strip():
        kept.pop(0)
    while kept and not kept[-1].strip():
        kept.pop()
    return "\n".join(kept)


def left_column(panel: dict) -> str:
    if panel.get("tex_proof"):
        raw = panel["tex_proof"]["raw"]
    else:
        raw = panel["tex_statement"]["raw"]
    return extract_tex_body(raw)


def right_column(panel: dict) -> str:
    blocks = [b["code"].rstrip() for b in panel.get("lean_blocks", [])]
    return "\n\n".join(blocks)


def heading(panel: dict) -> str:
    label = KIND_LABEL.get(panel["kind"], panel["kind"].capitalize())
    env_title = panel["tex_statement"]["env_title"]
    return f"{label}: {env_title}"


def render_row(panel: dict, preserved_notes: str) -> str:
    ref = panel["ref"]
    title = heading(panel)
    left = left_column(panel)
    right = right_column(panel)
    notes_body = preserved_notes if preserved_notes.strip() else ""
    return (
        f"%% ROW-BEGIN {ref}\n"
        f"\\subsection*{{{title}}}\n"
        f"\n"
        f"\\noindent\n"
        f"\\begin{{minipage}}[t]{{0.49\\textwidth}}\n"
        f"{left}\n"
        f"\\end{{minipage}}\\hfill\n"
        f"\\begin{{minipage}}[t]{{0.49\\textwidth}}\n"
        f"\\begin{{minted}}{{lean4}}\n"
        f"{right}\n"
        f"\\end{{minted}}\n"
        f"\\end{{minipage}}\n"
        f"\n"
        f"\\vspace{{0.5em}}\n"
        f"\\noindent\\textbf{{Notes:}}\\par\n"
        f"% NOTES-BEGIN {ref}\n"
        f"{notes_body}\n"
        f"% NOTES-END {ref}\n"
        f"\\vspace{{5em}}\n"
        f"\\noindent\\hrulefill\n"
        f"\\par\\bigskip\n"
        f"%% ROW-END {ref}\n"
    )


def load_existing_notes(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    text = path.read_text()
    return {m.group("ref"): m.group("body") for m in NOTES_BLOCK_RE.finditer(text)}


def main() -> None:
    manifest = json.loads((DATA_DIR / "manifest.json").read_text())
    preserved = load_existing_notes(OUT_PATH)

    out = [
        "% appendix.tex — generated by building_website/scripts/build_appendix.py.",
        "% Re-running the script preserves whatever sits between each row's",
        "% `% NOTES-BEGIN <ref>` / `% NOTES-END <ref>` markers, so hand-written",
        "% notes are never overwritten when panel data is refreshed.",
        "%",
        "% Preamble (documentclass, packages, custom macros, minted setup) is",
        "% supplied by the wrapping document; this file only emits body content.",
        "",
    ]

    for chapter in manifest["chapters"]:
        for section in chapter["sections"]:
            sec = section["section"]
            out.append(ROW_SEP)
            out.append(f"\\section*{{Section {sec}}}")
            out.append("")
            for row in section["rows"]:
                if not row.get("available", False):
                    continue
                panel_path = DATA_DIR / f"{row['ref']}.json"
                panel = json.loads(panel_path.read_text())
                out.append(render_row(panel, preserved.get(row["ref"], "")))

    OUT_PATH.write_text("\n".join(out).rstrip() + "\n")
    print(f"Wrote {OUT_PATH} ({OUT_PATH.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
